version: '3.7'

services:
  ad-admin-test:
    restart: always
    container_name: base-project
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "33063:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql