spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33063/base-project?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret: 89127391284091890863490852390458239048zjklsjdhalskjdklsdfjadklsj72